# Generated by Django 6.0 on 2025-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=16)),
                ('adress_dep', models.CharField(max_length=200)),
                ('adress_arr', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
